version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5
  maven: circleci/maven@0.0.12

jobs:
  codecov_upload:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - codecov/upload

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - codecov_upload
