version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  codecov: codecov/codecov@1.0.5

workflows:
  maven:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      build:
        steps:
          - codecov/upload
